# Lodestar root data directory
LODESTAR_CLI_BN_DATA_DIR=$SHARED_CONFIG_DATA_DIR

# Name of the Ethereum Consensus chain network to join
LODESTAR_CLI_BN_NETWORK=$SHARED_CONFIG_NETWORK

# File path to a shared hex-encoded JWT secret for authentication with the EL client's RPC server
LODESTAR_CLI_BN_JWT_SECRET=$SHARED_CONFIG_SECRETS_FILE

# URLs to execution client engine API
LODESTAR_CLI_BN_EXECUTION_URLS=$SHARED_CONFIG_ENDPOINT_URL

# Server URL hosting Beacon Node APIs to fetch weak subjectivity state
LODESTAR_CLI_BN_CHECKPOINT_SYNC_URL=$SHARED_CONFIG_CHECKPPOINT_SYNC_URL