# Minimal set of configs to make both the execution and consensus client online 

# dependent variables, non-client options 
# used in options creation 
EXECUTION_CLIENT=besu
CONSENSUS_CLIENT=lighthouse
EXECUTION_CLIENT_VERSION=24.5.1
CONSENSUS_CLIENT_VERSION=5.1.3

# shared options
# note these options ALWAYS overwrite the client specific options 
BASE_CONFIG_NETWORK=testnet
# PORT for EL and CL to communicate
BASE_CONFIG_ENGINE_API_PORT=8551
# URL for EL and CL to communicate
BASE_CONFIG_ENDPOINT_URL=http://localhost:$BASE_CONFIG_ENGINE_API_PORT
# DATADIR where CL and EL dirs will be placed
BASE_CONFIG_DATA_DIR=$HOME/nodes/$EXECUTION_CLIENT-$CONSENSUS_CLIENT/$BASE_CONFIG_NETWORK
# JWT secrets file shared by CL and EL
BASE_CONFIG_SECRETS_FILE=$BASE_CONFIG_DATA_DIR/jwt.hex


# custom network options 
BASE_CONFIG_TESTNET_DIR=$BASE_CONFIG_DATA_DIR/testnet
BASE_CONFIG_GENESIS_FILE=$BASE_CONFIG_TESTNET_DIR/genesis.json 
BASE_CONFIG_GENESIS_STATE=$BASE_CONFIG_TESTNET_DIR/genesis.ssz
SHARED_CHAINCONFIG=$BASE_CONFIG_TESTNET_DIR/consensus/config.yml

# FILLED IN BY SCRIPT, but custom network options (ephemery, testnet)
BASE_CONFIG_BOOTNODES=
BASE_CONFIG_BOOTNODES_ENODE=
BASE_CONFIG_NETWORK_ID=


# execution_client only options
BASE_CONFIG_EL_METRICS_PORT=
BASE_CONFIG_EL_WS_PORT=
BASE_CONFIG_EL_RPC_PORT=
BASE_CONFIG_EL_P2P_PORT=

# consensus_client only options 
BASE_CONFIG_BEACON_API_URL=
BASE_CONFIG_CHECKPPOINT_SYNC_URL=

BASE_CONFIG_METRICS_PORT=
BASE_CONFIG_CL_RPC_PORT=
BASE_CONFIG_CL_P2P_PORT=

# validator related options shared between consensus client & validator
SHARED_VALIDATOR_DATADIR=$BASE_CONFIG_DATA_DIR/validator-data
SHARED_VALIDATOR_BEACON_RPC_PROVIDER=localhost:4000
SHARED_NUM_VALIDATORS=64
SHARED_FEE_RECEIPENT_ADDRESS=0x123463a4b065722e99115d6c222f267d9cabb524