name: Mainnet tests


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  besu:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cl_name:
          - lighthouse
          # - lodestar
          # - nimbus-eth2
          # - prysm
          # - teku
      fail-fast: false
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Install java deps
          run: | 
            sudo apt remove --purge -y $(dpkg --list | grep openjdk | awk '{print $2}')
            JAVA_PKG=$(dpkg-query -S $(which java) | cut -d: -f1)
            if [ -n "$JAVA_PKG" ]; then
              sudo apt-get remove --purge -y $JAVA_PKG
            fi
            sudo apt remove --purge -y openjdk-17-jdk openjdk-17-jre default-jre default-jdk
            sudo apt-get autoremove --purge -y
            sudo apt-get clean
            sudo apt -y install wget curl
            wget -q https://download.oracle.com/java/21/archive/jdk-21.0.2_linux-x64_bin.deb
            sudo apt install ./jdk-21.0.2_linux-x64_bin.deb
            echo "export JAVA_HOME=/usr/lib/jvm/jdk-21/" | sudo tee /etc/profile.d/jdk.sh
            echo 'export PATH=$PATH:$JAVA_HOME/bin' | sudo tee -a /etc/profile.d/jdk.sh
            source /etc/profile.d/jdk.sh
            sudo ln -s /usr/lib/jvm/jdk-21-oracle-x64 /usr/lib/jvm/jdk-21
            java -version
        - name: Install dotnet
          run: | 
            sudo apt update
            sudo apt install -y aspnetcore-runtime-8.0
        - name: Install node.js dep
          run: | 
            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
            sudo apt install -y nodejs
        - name: add eth-nodes repository
          run: |
            sudo curl -fsSL https://packages.eth-pkg.com/keys/ethpkg-archive-keyring.asc -o /usr/share/keyrings/ethpkg-archive-keyring.asc
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/ethpkg-archive-keyring.asc] http://packages.eth-pkg.com/noble-main noble main" | sudo tee -a /etc/apt/sources.list.d/ethpkg.list
            sudo apt update
        - uses: awalsh128/cache-apt-pkgs-action@latest
          with:
            packages: |
              eth-node-besu eth-node-erigon eth-node-geth eth-node-nethermind eth-node-reth \ 
              eth-node-lighthouse eth-node-lodestar eth-node-nimbus-eth2 eth-node-prysm eth-node-teku \ 
              bats nohup
            version: 1.0  
        - name: Run test
          run: | 
            bats --show-output-of-passing-tests tests/test_mainnet.bats --filter besu-${{matrix.cl_name}}