name: testnet tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  besu:
      runs-on: ubuntu-24.04
      strategy:
        matrix:
          cl_name:
            - lighthouse
            - lodestar
            - nimbus-eth2
            - prysm
            - teku
        fail-fast: false
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          - uses: ./node-test
            with:
              network: testnet
              el_name: besu 
              cl_name: ${{matrix.cl_name}}
  # erigon:
  #     runs-on: ubuntu-24.04
  #     strategy:
  #       matrix:
  #         cl_name:
  #           - lighthouse
  #           - lodestar
  #           - nimbus-eth2
  #           - prysm
  #           - teku
  #       fail-fast: false
  #     steps:
  #         - name: Checkout code
  #           uses: actions/checkout@v4
    
  #         - uses: ./node-test
  #           with:
  #             network: testnet
  #             el_name: erigon 
  #             cl_name: ${{matrix.cl_name}}
  # geth:
  #     runs-on: ubuntu-24.04
  #     strategy:
  #       matrix:
  #         cl_name:
  #           - lighthouse
  #           - lodestar
  #           - nimbus-eth2
  #           - prysm
  #           - teku
  #       fail-fast: false
  #     steps:
  #         - name: Checkout code
  #           uses: actions/checkout@v4
    
  #         - uses: ./node-test
  #           with:
  #             network: testnet
  #             el_name: geth 
  #             cl_name: ${{matrix.cl_name}}

  # nethermind:
  #     runs-on: ubuntu-24.04
  #     strategy:
  #       matrix:
  #         cl_name:
  #           - lighthouse
  #           - lodestar
  #           - nimbus-eth2
  #           - prysm
  #           - teku
  #       fail-fast: false
  #     steps:
  #         - name: Checkout code
  #           uses: actions/checkout@v4
    
  #         - uses: ./node-test
  #           with:
  #             network: testnet
  #             el_name: nethermind 
  #             cl_name: ${{matrix.cl_name}}
  # reth:
  #     runs-on: ubuntu-24.04
  #     strategy:
  #       matrix:
  #         cl_name:
  #           - lighthouse
  #           - lodestar
  #           - nimbus-eth2
  #           - prysm
  #           - teku
  #       fail-fast: false
  #     steps:
  #         - name: Checkout code
  #           uses: actions/checkout@v4
    
  #         - uses: ./node-test
  #           with:
  #             networK: testnet
  #             el_name: reth 
  #             cl_name: ${{matrix.cl_name}}
